baseURL = "http://worldpotato.github.io/"
languageCode = "en-us"
title = "Worldpotato"
theme = "hugo-notepadium"

# custom navigation items
# light/dark mode
[params]
style = "auto"  # default: "auto", based on system. "light": light theme, "dark": dark theme.
licence = "CC-BY-SA"

[params.nav]
showTags = true             # /tags/

[[params.nav.custom]]
title = "About"
url = "/about/about/"

[[params.nav.custom]]
title = "University"
url = "/university"

[[params.nav.custom]]
title = "Linux"
url = "/linux"

[[params.nav.custom]]
title = "Development"
url = "/development"

# syntax highlighting
[params.syntax]
use = "none"  # builtin: "prismjs", "hljs". "none" means Chroma
theme = "dracula"
darkTheme = "xcode-dark"  # apply this theme in dark mode

