baseURL = "http://worldpotato.github.io"
languageCode = "en-us"
title = "Worldpotato"
copyright = "CC-BY-SA Worldpotato."
theme = "hugo-notepadium"

# custom navigation items
# light/dark mode
[params]
style = "auto"  # default: "auto", based on system. "light": light theme, "dark": dark theme.
licence = "CC-BY-SA"
slogan = "Me and my potato world"

[params.nav]
showTags = true             # /tags/
dateFormat = "Monday, January 2, 2006"

[[params.nav.custom]]
title = "About"
url = "/about"

[[params.nav.custom]]
title = "University"
url = "/posts/university"

[[params.nav.custom]]
title = "Linux"
url = "/posts/linux"

[[params.nav.custom]]
title = "Development"
url = "/posts/development"

# syntax highlighting
[params.syntax]
use = "none"  # builtin: "prismjs", "hljs". "none" means Chroma
theme = "dracula"
darkTheme = "xcode-dark"  # apply this theme in dark mode

[markup.highlight]
codeFences = true
noClasses = false
